### ISSUE TITLE
[Bug] swc build error

### ISSUE THREAD

**Issue by brian-patrick-3** [storybookjs/addon-webpack5-compiler-swc#12]
### Describe the bug

Getting the following error executing build-storybook in our CI env:

```bash
10:46:51 AM: Module build failed (from ./node_modules/swc-loader/src/index.js):
10:46:51 AM: Error: Failed to load native binding
10:46:51 AM:     at Object.<anonymous> (./node_modules/@swc/core/binding.js:329:11)
10:46:51 AM:     at Module._compile (node:internal/modules/cjs/loader:1469:14)
10:46:51 AM:     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
10:46:51 AM:     at Object.newLoader (./node_modules/esbuild-register/dist/node.js:2262:9)
10:46:51 AM:     at extensions..js (./node_modules/esbuild-register/dist/node.js:4838:24)
10:46:51 AM:     at Module.load (node:internal/modules/cjs/loader:1288:32)
10:46:51 AM:     at Module._load (node:internal/modules/cjs/loader:1104:12)
10:46:51 AM:     at Module.require (node:internal/modules/cjs/loader:1311:19)
10:46:51 AM:     at require (node:internal/modules/helpers:179:18)
10:46:51 AM:     at Object.<anonymous> (./node_modules/@swc/core/index.js:49:17)
10:46:51 AM: Module build failed: Error: Failed to load native binding
10:46:51 AM:     at Object.<anonymous> (./node_modules/@swc/core/binding.js:329:11)
10:46:51 AM:     at Module._compile (node:internal/modules/cjs/loader:1469:14)
10:46:51 AM:     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
10:46:51 AM:     at Object.newLoader (./node_modules/esbuild-register/dist/node.js:2262:9)
10:46:51 AM:     at extensions..js (./node_modules/esbuild-register/dist/node.js:4838:24)
10:46:51 AM:     at Module.load (node:internal/modules/cjs/loader:1288:32)
10:46:51 AM:     at Module._load (node:internal/modules/cjs/loader:1104:12)
10:46:51 AM:     at Module.require (node:internal/modules/cjs/loader:1311:19)
10:46:51 AM:     at require (node:internal/modules/helpers:179:18)
10:46:51 AM:     at Object.<anonymous> (./node_modules/@swc/core/index.js:49:17)
```

@netlify/build 29.56.1
Node 18 & 20

Full log: https://app.netlify.com/sites/shidoka-icons/deploys/6762fc4877125021a8c0a455

**Comment by Armanio** [comment]
Hi!
I found a workaround: downgrade `@storybook/addon-webpack5-compiler-swc` to 1.0.4 will fix it
